#pragma config(Sensor, S1,     eyes,           sensorAnalog)
#pragma config(Motor,  motorA,          mA,            tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorB,          mB,            tmotorNXT, openLoop, encoder)
#pragma config(Motor,  motorC,          mC,            tmotorNXT, openLoop, encoder)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	nMotorEncoder[mB] = 0; // reset the Motor Encoder of Motor B
	nMotorEncoderTarget[mB] = 60; // set the  target for Motor Encoder of Motor B to 360

	motor[mB] = 75; // motor B is run at a power level of 75

	while(nMotorRunState[mB]!=runStateIdle)// while Motor B is still running (hasn't reached target yet):
	{
		// do not continue
	}
	motor[mB] = 0; // motor B is stopped at a power level of 0


}
